### ISSUE TITLE
Weather Forecast and Javascript Implementation

### ISSUE THREAD

**Issue by smcgarr13** [smcgarr13/JoyRide#3]
# Weather Forecast and Javascript Implementation

## User Story
As a user, I want to input different parameters when planning a route and have one dynamically generated. 

## Acceptance Criteria 
It’s done
- When the application leverages a Weather API
- When the application is interactive
- When the application uses client-side storage to store persistent data
- When JQuery is integrated into the programming

**Comment by smcgarr13** [comment]
N/A

**Comment by BaldOracle** [comment]
Added weather code.
